# Définit les étapes du pipeline dans un ordre logique :
# lint (vérification rapide de code)
#   -> build (construction)
#     -> test (tests unitaires et de couverture)
#       -> deploy (déploiement)
stages:
  - lint
  - build
  - test
  - deploy

# -----------------
# Configuration globale
# -----------------

# Utilise l'image Docker officielle de Python
image: python:3.13-slim

# -----------------
# 1. Étape LINT : Vérification rapide du style et de la qualité du code
# -----------------
lint_job:
  stage: lint
  allow_failure: true
  script:
    # Installe Poetry pour exécuter les outils de lint
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install --no-root --directory server
    # Exécute les vérifications de formatage et de typage
    - cd server
    - poetry run black --check .
    - poetry run isort --check-only .
    - poetry run mypy app


# -----------------
# 2. Étape BUILD : Installation des dépendances et création de l'environnement
# -----------------
build_job:
  stage: build
  script:
    - pip install poetry
    # Configure Poetry pour créer l'environnement virtuel dans le dossier du projet
    - poetry config virtualenvs.in-project true
    # Installe toutes les dépendances du projet, y compris les dépendances de développement
    - poetry install --no-root --directory server
  artifacts:
    paths:
      # Sauvegarde le dossier de l'environnement virtuel (.venv) en tant qu'artefact
      - server/.venv/
    expire_in: 1 hour # L'artefact sera supprimé après 1 heure


# -----------------
# 3. Étape TEST : Exécution des tests en utilisant l'environnement construit
# -----------------
test_job:
  stage: test
  script:
    - pip install poetry
    - cd server
    # Réactive l'environnement virtuel qui a été téléchargé depuis l'artefact de 'build_job'
    - source .venv/bin/activate
    # Exécute les tests unitaires
    - poetry run pytest --junitxml=test-report.xml
  needs:
    - build_job
  artifacts:
    when: always
    reports:
      # Génère un rapport de test au format JUnit
      junit: server/test-report.xml
    paths:
      - server/test-report.xml
    expire_in: 15 days


# -----------------
# 4. Étape DEPLOY : Déploiement en production
# -----------------
deploy_job:
  stage: deploy
  script:
    - echo "Script de déploiement..."
  environment: production
  rules:
    # S'exécute uniquement lors d'un push ou merge sur la branche 'main'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs:
    - test_job
