# Définit les étapes du pipeline dans un ordre logique :
# lint (vérification rapide de code)
#   -> build (construction)
#     -> test (tests unitaires et de couverture)
#       -> deploy (déploiement)
stages:
  - lint
  - build
  - test
  - deploy

include:
  - '/ci/server.yml'
  - '/ci/client.yml'
