# Définit les étapes du pipeline dans un ordre logique :
# lint (vérification rapide de code)
#   -> build (construction)
#     -> test (tests unitaires et de couverture)
#       -> deploy (déploiement)
stages:
  - lint
  - build
  - test
  - deploy

# Définit un modèle réutilisable pour le déploiement Docker
.docker_deploy_template:
  stage: deploy
  image: docker:27
  services:
    - docker:27-dind # Démarre le service Docker-in-Docker
  environment: production
  before_script:
    # Se connecte à Docker Hub
    - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_TOKEN"
  rules:
    # Ne s'exécute que lorsque le code est poussé sur la branche par défaut (généralement 'main')
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

include:
  - '/ci/server.yml'
  - '/ci/client.yml'
