[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors = ["Zineddine CHIKHAOUI <zinedine@datategy.net>"]
readme = "README.md"

packages = [{include = "app"}]

[tool.poetry.dependencies]
python = ">=3.13"
fastapi = ">=0.117.1,<0.118.0"
uvicorn = ">=0.37.0,<0.38.0"
pillow = "^11.0.0"
sqlalchemy = ">=2.0.43,<3.0.0"
pydantic = { extras = ["email"], version = ">=2.11.9,<3.0.0" }
passlib = ">=1.7.4,<2.0.0"
httpx = ">=0.28.1,<0.29.0"
bcrypt = ">=3.0.0,<4.0.0"
motor = ">=3.7.1,<4.0.0"
pymongo = "^4.15.3"
python-dotenv = ">=1.0.0,<2.0.0"
PyJWT = ">=2.7.0,<3.0.0"
python-multipart = ">=0.0.6,<1.0.0"
mongomock = "^4.3.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=8.4.2,<9.0.0"
pytest-asyncio = ">=1.2.0,<2.0.0"
black = "^25.9.0"
isort = "^6.0.1"
mypy = "^1.18.2"
types-passlib = "^1.7.7.20250602"
mongomock = "^4.2.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
